# Generated by Django 2.2.4 on 2024-05-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='books',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='users',
            new_name='user',
        ),
    ]
